// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHSsjZoyrit2OqYBVfmv1WWm7_ZP7xyw',
    appId: '1:635528700092:web:8018ca2b31076988ca30b9',
    messagingSenderId: '635528700092',
    projectId: 'hanhstore-13dc3',
    authDomain: 'hanhstore-13dc3.firebaseapp.com',
    storageBucket: 'hanhstore-13dc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Ljg1MjB1AgKy9wZVkq_-xy-LWitnTNw',
    appId: '1:635528700092:android:9d42c1368d6d6e4cca30b9',
    messagingSenderId: '635528700092',
    projectId: 'hanhstore-13dc3',
    storageBucket: 'hanhstore-13dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzsK-I3XsU9A1-P7WulyOV-micc88xv0',
    appId: '1:635528700092:ios:176c16e62f404225ca30b9',
    messagingSenderId: '635528700092',
    projectId: 'hanhstore-13dc3',
    storageBucket: 'hanhstore-13dc3.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzzsK-I3XsU9A1-P7WulyOV-micc88xv0',
    appId: '1:635528700092:ios:28abd4a3d550190cca30b9',
    messagingSenderId: '635528700092',
    projectId: 'hanhstore-13dc3',
    storageBucket: 'hanhstore-13dc3.appspot.com',
    iosBundleId: 'com.example.emartApp.RunnerTests',
  );
}
